/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROO2EXP
#define ROO2EXP

#include "RooAbsPdf.h"
#include "RooRealProxy.h"

class Roo2Exp : public RooAbsPdf {
public:
  Roo2Exp() {} ;
  Roo2Exp(const char *name, const char *title,
	  RooAbsReal& _m,
	  RooAbsReal& _m0,
	  RooAbsReal& _tau1,
	  RooAbsReal& _tau2);
  Roo2Exp(const Roo2Exp& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Roo2Exp(*this,newname); }
  inline virtual ~Roo2Exp() { } 

  virtual Int_t getAnalyticalIntegral( RooArgSet& allVars,  RooArgSet& analVars, const char* rangeName=0 ) const;
  virtual Double_t analyticalIntegral( Int_t code, const char* rangeName=0 ) const;

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy tau1 ;
  RooRealProxy tau2 ;

  Double_t evaluate() const ;

private:

  //  ClassDef(Roo2Exp,1) // Your description goes here...
};


#endif
