/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROO2SUMEXP
#define ROO2SUMEXP

#include "RooAbsPdf.h"
#include "RooRealProxy.h"

class Roo2SumExp : public RooAbsPdf {
public:
  Roo2SumExp() {} ;
  Roo2SumExp(const char *name, const char *title,
	  RooAbsReal& _m,
	  RooAbsReal& _A,
	  RooAbsReal& _tau1,
	  RooAbsReal& _tau2);
  Roo2SumExp(const Roo2SumExp& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Roo2SumExp(*this,newname); }
  inline virtual ~Roo2SumExp() { } 

  virtual Int_t getAnalyticalIntegral( RooArgSet& allVars,  RooArgSet& analVars, const char* rangeName=0 ) const;
  virtual Double_t analyticalIntegral( Int_t code, const char* rangeName=0 ) const;

protected:

  RooRealProxy m ;
  RooRealProxy A ;
  RooRealProxy tau1 ;
  RooRealProxy tau2 ;

  Double_t evaluate() const ;

private:

  //  ClassDef(Roo2SumExp,1) // Your description goes here...
};


#endif
