/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOARGUSGAUSS
#define ROOARGUSGAUSS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TObject.h"
#include <cmath>

class RooArgusGauss : public RooAbsPdf {
public:
  RooArgusGauss() {} ;
  RooArgusGauss(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _c,
	      RooAbsReal& _p,
	      RooAbsReal& _sigma);
  RooArgusGauss(const RooArgusGauss& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooArgusGauss(*this,newname); }
  inline virtual ~RooArgusGauss() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy c ;
  RooRealProxy p ;
  RooRealProxy sigma ;

  Double_t evaluate() const ;

private:

  Double_t argus(Double_t) const ;
  Double_t gauss(Double_t) const ;

  //  ClassDef(RooArgusGauss,1) // Your description goes here...
};

#endif
